package detersl:api@0.2.0; 

interface func-handler {
    record event {
        data: string,
    }

    record output {
        data: string
    }
    
    handle: func(event: event) -> output;
}


