package detersl:func-api@0.1.0; 

interface handler {
    record event {
        data: string,
    }

    record output {
        data: string
    }
    
    handle: func(event: event) -> output;
}

world func-handler-api {
    export handler;
}
